version: 2.1

orbs:
  rn: react-native-community/react-native@4.2.0

jobs:
  checkout_code:
    executor: rn/linux_js
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths: .
  analyse:
    executor: rn/linux_js
    steps:
      - attach_workspace:
          at: .
      - rn/yarn_install
      - run:
          name: Lint JS Code (ESLint)
          command: yarn run validate:eslint
      - run:
          name: TypeScript
          command: yarn run validate:typescript
      - run:
          name: Jest
          command: yarn run test:jest
  publish:
    executor: rn/linux_js
    steps:
      - attach_workspace:
          at: .
      - rn/yarn_install
      - run:
          name: Publish to NPM
          command: yarn ci:publish

workflows:
  test:
    jobs:
      - checkout_code
      - analyse:
          requires:
            - checkout_code
      - rn/android_build:
          project_path: "example/android"
          build_type: release
          requires:
            - analyse
      - rn/android_test:
          detox_configuration: "android.emu.release"
          detox_loglevel: "trace"
          requires:
            - rn/android_build
      - rn/ios_build_and_test:
          checkout: true
          attach_workspace: false
          pod_install_directory: "example/ios"
          project_type: "workspace"
          project_path: "example/ios/NetInfoExample.xcworkspace"
          derived_data_path: "example/ios/build"
          device: "iPhone Xs"
          build_configuration: "Release"
          scheme: "NetInfoExample"
          detox_configuration: "ios.sim.release"
          detox_loglevel: "trace"
          requires:
            - analyse
      - publish:
          requires:
            - analyse
            - rn/ios_build_and_test
            - rn/android_test
          filters:
            branches:
              only: master
